#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --output=finaltestoutput_%A.out
#SBATCH --partition=gpu
#SBATCH --time=4:00:00


# set path
export nnUNet_raw="path/to/nnUNet_raw"
export nnUNet_preprocessed="path/to/nnUNet_preprocessed"
export nnUNet_results="path/to/nnUNet_results"


nnUNetv2_predict -i test_set -o testset_out_final -d 900 -c 3d_fullres
